<Project Sdk="Godot.NET.Sdk/4.7.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Heroes1918</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Sim\Sim.csproj" />
    <ProjectReference Include="..\src\Lockstep\Lockstep.csproj" />
  </ItemGroup>

</Project>
